### ISSUE TITLE
osm2pgsql --append to existing imported slim database takes ages

### ISSUE THREAD

**Issue by a14stoner** [osm2pgsql-dev/osm2pgsql#2266] opened 2024-10-23 05:57 UTC
## What version of osm2pgsql are you using?

2024-10-23 05:42:44  osm2pgsql version 1.11.0
Build: None
Compiled using the following library versions:
Libosmium 2.20.0
Proj [API 6] 9.4.0
Lua 5.3.6

## What operating system and PostgreSQL/PostGIS version are you using?

PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

## Tell us something about your system

Its a bare metal server: 
- 20CPU
- 94GB RAM
- 6TB Raid5 HDD Storage

## What did you do exactly?

- downloaded [europe-latest](https://download.geofabrik.de/europe-latest.osm.pbf)
- extracted only Germany, Austria and Swizerland (BBOX: 1061543 5845974 1944529 6328993) with osmosis
- imported this dump with the following command: 
`osm2pgsql --hstore --slim -G -C 32000 -H POSTGIS --number-processes 32 -S /usr/local/renderd/scripts/osm2pgsql-replication/scripts/carto/openstreetmap-carto.style --tag-transform-script /usr/local/renderd/scripts/osm2pgsql-replication/scripts/carto/openstreetmap-carto.lua  -d DE_AT_CH-U gis dach_20241018.osm.pbf`
- the import was sucessful: osm2pgsql took 17033s (4h 43m 53s) overall.
- from the pbf export i got the export timestamp 2024-10-20T20:21:34Z 
- with this timestamp i downloaded the changefiles via pyosmium-get-changes
- with trim_osc.py i trimmed the changes down to my extend above:
- 103M    newchange.osc.gz
- 27M     newchange_trim.osc.gz
- then i wanted to append the changes to my before freshly importted database with this command: 
`osm2pgsql --append --slim -d DE_AT_CH -U gis -H POSTGIS  -C 30000 --number-processes 20 --multi-geometry --tag-transform-script /usr/local/renderd/scripts/pyosmium/openstreetmap-carto.lua -S /usr/local/renderd/scripts/pyosmium/openstreetmap-carto.style --expire-tiles=17-18 --expire-output=/usr/local/renderd/scripts/pyosmium/dirty_tiles.txt /usr/local/renderd/scripts/pyosmium/newchange_trim.osc.gz`

## What did you expect to happen?

when i import only the changes from 2 days of my extend i expect that the import is finished at least in some hours. 

## What did happen instead?

right now i waited 15 hours - the import only came to this step: 

```
2024-10-22 14:40:34  osm2pgsql version 1.11.0
2024-10-22 14:40:34  Database version: 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
2024-10-22 14:40:34  PostGIS version: 3.3
2024-10-22 14:40:34  Loading properties from table '"public"."osm2pgsql_properties"'.
2024-10-22 14:40:34  Not using flat node file (same as on import).
2024-10-22 14:40:34  Using prefix 'planet_osm' (same as on import).
2024-10-22 14:40:34  Using output 'pgsql' (same as on import).
2024-10-22 14:40:34  Using style file '/usr/local/renderd/scripts/pyosmium/openstreetmap-carto.style' (same as on import).
2024-10-22 14:40:34  Setting up table 'planet_osm_point'
2024-10-22 14:40:34  Setting up table 'planet_osm_line'
2024-10-22 14:40:34  Setting up table 'planet_osm_polygon'
2024-10-22 14:40:34  Setting up table 'planet_osm_roads'
Processing: Node(400k 13.8k/s) Way(0k 0.00k/s) Relation(0 0.0/s)
```

its loading the nodes until 400k - i think in the newchange_trim.osc.gz 400k nodes have changed?

## What did you do to try analyzing the problem?

I started up the import multiple times but i cannot find out why its stuck. 
One thing i analyzed is this: 

![grafik](https://github.com/user-attachments/assets/d6bd951c-a896-41d7-ba51-152780d43df8)

can it be that it takes ages to finish these 2 statements: 

`COPY "public"."planet_osm_nodes" FROM STDIN`

or

```
INSERT INTO osm2pgsql_changed_ways                
SELECT w.id                                                                                              
FROM "public"."planet_osm_ways" w, osm2pgsql_changed_nodes n                
WHERE w.nodes && ARRAY[n.id]
```
i think its the second one since this is in an active state

also i see that the database is doing something since i see a process which is taking one cpu entirely: 

![grafik](https://github.com/user-attachments/assets/6c6e5795-319b-49c3-9710-54c29fda3607)

For fully information i also put here my postgresql.conf

```
# DB Version: 15
# OS Type: linux
# DB Type: dw
# Total Memory (RAM): 94 GB
# CPUs num: 20
# Connections num: 1000
# Data Storage: hdd

max_connections = 1000
shared_buffers = 24064MB
effective_cache_size = 72192MB
maintenance_work_mem = 2GB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 500
random_page_cost = 4
effective_io_concurrency = 2
work_mem = 1232kB
huge_pages = try
min_wal_size = 4GB
max_wal_size = 16GB
max_worker_processes = 20
max_parallel_workers_per_gather = 10
max_parallel_workers = 20
max_parallel_maintenance_workers = 4

autovacuum_work_mem = 4GB
wal_level = minimal
checkpoint_timeout = 60min
max_wal_senders = 0
full_page_writes=off
fsync=off
jit=off
```
this is only the part i edited. got the values from pgtune. and the ones below i got from several forums and openstreetmap-carto INSTALL.md. Especially the jit parameter. 

My main goal would be to have an up to date database by doing 5 minutely updates. since this is taking hours i can forget it. is this is not doable faster i need to switch back to complete reimports ;)

Thanks in advance

**Comment by joto** [comment] 2024-10-23 07:24
Thanks for your detailed report. We have seen similiar problems before, but with much larger change files. It seems this can happen also with smaller change files. The problem is indeed the `INSERT INTO osm2pgsql_changed_ways ...` query. For some reason PostgreSQL chooses a really bad plan for this rather simple query and the query then takes forever. Maybe this is related to the PostgreSQL version or something else we have not understood yet, because this works perfectly well in other cases. (Which also means that generally minutely updates do work fine, the change files are small and updates are fast.)

Apart from the PostgreSQL version, I can see two things that are "special" in your setup that could affect this: The setting for `default_statistics_target` is much higher than the default, generally this should *improve* the planner results, but who knows. The other thing is that you are only using DACH data and not the planet. In DACH the data is much "denser" than the average for the planet, so maybe this has something to do with it.

The idle `COPY` command should hopefully not affect this. But you could try osm2pgsql 2.0.0 where this issue is fixed and the COPY command is closed much earlier.

**Comment by a14stoner** [comment] 2024-10-23 07:27
thanks for your thoughts. I am confident we will solve this issue. 
Do i need to make a full new import or can i --append with version 2.0.0 to a import which was made with version 1.11.0 ?

**Comment by mboeringa** [comment] 2024-10-23 08:15
@a14stoner 

One other thing I noticed is that you are still using HDD. The osm2pgsql manual clearly recommends (NVMe) SSDs due to the need for fast random access during some stages of the processing:

https://osm2pgsql.org/doc/manual.html#disk

Even if you can swap out the disks for only a single SATA SSD drive, it might help the processing speed. However, NVMe PCIe adaptors and a relatively small 1TB NVMe drive should cost you little, and be easy to install in older hardware.

**Comment by a14stoner** [comment] 2024-10-23 09:21
> @a14stoner
> 
> One other thing I noticed is that you are still using HDD. The osm2pgsql manual clearly recommends (NVMe) SSDs due to the need for fast random access during some stages of the processing:
> 
> https://osm2pgsql.org/doc/manual.html#disk
> 
> Even if you can swap out the disks for only a single SATA SSD drive, it might help the processing speed. However, NVMe PCIe 3.0 4x/8x/16x adaptors and a relatively small 1TB NVMe drive should cost you little, and be easy to install in older hardware.

doe to the budget reasons i cant get ssds in my company for this server ;(



> Hm. Just noticed something weird. The offending query looks like you are using the old middle database format. But from the command line it looks like you are using the new one. Can you show us the contents of the osm2pgsql_properties table?

This is the result: 

![grafik](https://github.com/user-attachments/assets/41d851c9-1f8c-44d2-999d-646a1bb8b706)

**Comment by joto** [comment] 2024-10-23 09:35
Okay, you do have the new database format. But it looks like you don't have a bucket index, which is even stranger. Can you check which indexes there are with `\di` and show us the result of `SELECT relname FROM pg_class WHERE relkind='i' AND relname = 'planet_osm_ways_nodes_bucket_idx';`?

**Comment by a14stoner** [comment] 2024-10-23 10:22
It has nothing in it. with this name. 

Maybe this all does not work because: 

Initially i made the import with -p 5432 . Yes with a small p and not a big one. so the prefix was 5432. all the tables and indexes were created with the prefix 5432. I did not want to do a import again to i simply renamed the tables. can it be that the indexes dont work anymore because i renamed the tables?

**Comment by joto** [comment] 2024-10-23 12:10
Ah, that explains everything. I'll put a warning in the docs that you are not supposed to mess with table names etc. I am pretty sure this will solve your problem.

**Comment by a14stoner** [comment] 2024-10-24 13:09
Sooo reimport was finished after 4 hrs: 

```
2024-10-23 10:52:47  Initializing properties table '"public"."osm2pgsql_properties"'.
2024-10-23 10:52:47  Storing properties to table '"public"."osm2pgsql_properties"'.
2024-10-23 10:52:47  Setting up table 'planet_osm_point'
2024-10-23 10:52:47  Setting up table 'planet_osm_line'
2024-10-23 10:52:47  Setting up table 'planet_osm_polygon'
2024-10-23 10:52:47  Setting up table 'planet_osm_roads'
2024-10-23 14:48:18  Reading input files done in 14131s (3h 55m 31s).
2024-10-23 14:48:18    Processed 929262586 nodes in 2303s (38m 23s) - 404k/s
2024-10-23 14:48:18    Processed 127236293 ways in 6439s (1h 47m 19s) - 20k/s
2024-10-23 14:48:18    Processed 1932984 relations in 5389s (1h 29m 49s) - 359/s
2024-10-23 14:48:19  Done postprocessing on table 'planet_osm_nodes' in 0s
2024-10-23 14:48:19  Building index on table 'planet_osm_ways'
2024-10-23 14:48:19  Building index on table 'planet_osm_rels'
2024-10-23 14:48:19  Clustering table 'planet_osm_polygon' by geometry...
2024-10-23 14:48:19  Clustering table 'planet_osm_point' by geometry...
2024-10-23 14:48:19  Clustering table 'planet_osm_roads' by geometry...
2024-10-23 14:48:19  Clustering table 'planet_osm_line' by geometry...
2024-10-23 14:49:41  Creating geometry index on table 'planet_osm_roads'...
2024-10-23 14:49:51  Creating osm_id index on table 'planet_osm_roads'...
2024-10-23 14:49:53  Analyzing table 'planet_osm_roads'...
2024-10-23 14:54:58  Creating geometry index on table 'planet_osm_point'...
2024-10-23 14:58:44  Creating osm_id index on table 'planet_osm_point'...
2024-10-23 14:59:44  Analyzing table 'planet_osm_point'...
2024-10-23 15:02:51  Creating geometry index on table 'planet_osm_line'...
2024-10-23 15:05:08  Creating osm_id index on table 'planet_osm_line'...
2024-10-23 15:05:31  Analyzing table 'planet_osm_line'...
2024-10-23 15:25:36  Creating geometry index on table 'planet_osm_polygon'...
2024-10-23 15:31:47  Creating osm_id index on table 'planet_osm_polygon'...
2024-10-23 15:32:49  Analyzing table 'planet_osm_polygon'...
2024-10-23 15:33:30  Done postprocessing on table 'planet_osm_ways' in 2711s (45m 11s)
2024-10-23 15:33:30  Done postprocessing on table 'planet_osm_rels' in 186s (3m 6s)
2024-10-23 15:33:30  All postprocessing on table 'planet_osm_point' done in 688s (11m 28s).
2024-10-23 15:33:30  All postprocessing on table 'planet_osm_line' done in 1082s (18m 2s).
2024-10-23 15:33:30  All postprocessing on table 'planet_osm_polygon' done in 2674s (44m 34s).
2024-10-23 15:33:30  All postprocessing on table 'planet_osm_roads' done in 98s (1m 38s).
2024-10-23 15:33:30  Storing properties to table '"public"."osm2pgsql_properties"'.
2024-10-23 15:33:30  osm2pgsql took 16843s (4h 40m 43s) overall.
```

Afterwards I created openstreetmap-carto indicies.

Then i downloaded the changes from sequence 6312535 to  (about 4 days of changes)  and trimmed it downt to my extend (took aaaages.. )
286M    newchange.osc.gz
61M     newchange_trim.osc.gz

and made a new import with `--append` .

```
osm2pgsql version 2.0.0 (2.0.0)
2024-10-24 12:47:23  Database version: 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
2024-10-24 12:47:23  PostGIS version: 3.3
2024-10-24 12:47:24  Loading properties from table '"public"."osm2pgsql_properties"'.
2024-10-24 12:47:25  Not using flat node file (same as on import).
2024-10-24 12:47:25  Using prefix 'planet_osm' (same as on import).
2024-10-24 12:47:25  Using output 'pgsql' (same as on import).
2024-10-24 12:47:25  Using the style file you specified on the command line ('/usr/local/renderd/scripts/pyosmium/openstreetmap-carto.style') instead of the one used on import ('/usr/local/renderd/scripts/osm2pgsql-replication/scripts/carto/openstreetmap-carto.style').
2024-10-24 12:47:25  Storing properties to table '"public"."osm2pgsql_properties"'.
2024-10-24 12:47:26  WARNING: The pgsql (default) output is deprecated. For details see https://osm2pgsql.org/doc/faq.html#the-pgsql-output-is-deprecated-what-does-that-mean
2024-10-24 12:47:26  Storing properties to table '"public"."osm2pgsql_properties"'.
2024-10-24 12:47:26  Setting up table 'planet_osm_point'
2024-10-24 12:47:26  Setting up table 'planet_osm_line'
2024-10-24 12:47:26  Setting up table 'planet_osm_polygon'
2024-10-24 12:47:26  Setting up table 'planet_osm_roads'
Processing: Node(1320k 4.1k/s) Way(0k 0.00k/s) Relation(0 0.0/s)
```

One thing i noticed. the import with v2.0.0 is much slower: 

v1.11.0: Processing: Node(400k 13.8k/s
v2.0.0:   Processing: Node(1320k 4.1k/s

It stays at the same statement as the last time: 

![grafik](https://github.com/user-attachments/assets/ca041f73-b6a1-45bc-be2a-74c36ae96192)

the requested index is here now: 

![grafik](https://github.com/user-attachments/assets/143dbf5a-72fa-4e7f-92b1-b21d4fd3b451)

i will let it run over the night and see how fast it goes. 
I will report back my results tomorrow ;)

**Comment by joto** [comment] 2024-10-24 15:06
It is doing the right query now (`SELECT osm2pgsql_find_changed_ways()`), so it is using the index. That's good. There is still the open COPY which should not be there, I need to investigate that.

Yes, the whole thing is not very fast, but it is not hanging any more as it was before, it is making progress. It has been a long time since I have seen a system with spinning disk. So I am not sure any remaining problem you are seeing is not due to disk I/O. Before you saw the postgres using 100% CPU in state R. Is that still the case?

The processing log lines are interesting. You quote these:

Processing: Node(1320k 4.1k/s
Processing: Node(1325k 0.9k/s)

So the last 5k nodes were really really slow? Could well be that a vacuum or checkpoint or whatever came in there. That's why those numbers are only marginally useful, there can always be something else running there.

In general: There might be some slowdown in newer versions compared to older version due to the different way we are finding the ways/relations we have to reprocess because of changed nodes. We are doing somewhat more work than before. I have not seen such slowdowns on SSDs, but it might well be that they show up on HDDs. But there isn't anything we can do about that.

You might want to look into using a flat node file. For your use case it might be better or worse, hard to say.

**Comment by a14stoner** [comment] 2024-10-25 06:20
Good Morning, 

the import now works well and i can do updates 5 minutely. Thats all i need. 

The original issue was renaming the tables after the import. We solved that. 

IMO we can close this issue. 

@joto do you want to further investigate the open COPY or should we just skip it since it works well now?

**Comment by joto** [comment] 2024-10-25 07:32
I tested it locally and the COPY was gone in my case. Sometimes the output of pg_stat_activity is confusing, because it shows the last command that was run, even if it is not active any more. So only the commands in state=active are really relevant. We don't have that column in the last case you showed, but in the first case the connection is in state=idle, so I believe this is okay.

I'll close this now.

**Closed by joto** 2024-10-25 07:32 UTC
